default: &default
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  adapter: mysql2
  username: root
  password: root
  host: mysql

development:
  <<: *default
  database: blog_sample

test:
  <<: *default
  database: blog_sample

production:
  <<: *default
  database: blog_sample_prd
  username: admin
  password: password
  host: SET_YOUR_RDS_HOST
